/** Mirrors backend/src/constants/permissions.js. The backend remains the authority. */
export const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: 'dashboard.view',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_UPDATE: 'products.update',
  PRODUCTS_DELETE: 'products.delete',
  MASTERS_MANAGE: 'masters.manage',
  GST_MANAGE: 'gst.manage',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_IN: 'inventory.in',
  INVENTORY_OUT: 'inventory.out',
  INVENTORY_ADJUST: 'inventory.adjust',
  TRANSFER_REQUEST: 'transfer.request',
  TRANSFER_APPROVE: 'transfer.approve',
  TRANSFER_RECEIVE: 'transfer.receive',
  BRANCHES_MANAGE: 'branches.manage',
  BRANCHES_ALL: 'branches.all',
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_MANAGE: 'customers.manage',
  INVOICE_VIEW: 'invoice.view',
  INVOICE_CREATE: 'invoice.create',
  INVOICE_UPDATE: 'invoice.update',
  INVOICE_CANCEL: 'invoice.cancel',
  REPORTS_VIEW: 'reports.view',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  SETTINGS_MANAGE: 'settings.manage',
  AUDIT_VIEW: 'audit.view',
});
